In [2]:
import pandas as pd
from word2number import w2n

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [93]:
#As always we need to read the training data
df = pd.read_csv('E:\\py-master\\ML\\2_linear_reg_multivariate\\Exercise\\hiring.csv')
df.head(7)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000

In [94]:
#filling missing experience with one
df["experience"].fillna("zero", inplace = True)  

In [95]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [96]:
#As we have replaced missing data, now we need to convert that into number
#For the experience column
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [97]:
#Now replacing the test_score NaN with the median values. For replacing the NaN we are taking the median of the col 
import math
median_score = math.floor((df.loc[:,"test_score(out of 10)"].median())) #Calculate specific col median
#Now, replacing NaN in test_score
df['test_score(out of 10)'].fillna(median_score , inplace = True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [99]:
#Now as we have preprocssed our data. We are ready to go with fitting the data
reg = linear_model.LinearRegression(); #Creating a regression object
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [100]:
#Now we are ready to predict
reg.predict([[2,9,6]])

array([53205.96797671])

In [101]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [102]:
reg.predict([[0,8,7]])

array([47939.59243086])